stages:
  preprocess:
    cmd: bash -c 'set -a; [ -f .env ] && . .env || true; set +a; python src/data/make_dataset.py'
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/preprocessed/interim_dataset.csv
  build_features:
    cmd: bash -c 'set -a; [ -f .env ] && . .env || true; set +a; python src/features/build_features.py'
    deps:
    - data/preprocessed/interim_dataset.csv
    - src/features/build_features.py
    outs:
    - data/preprocessed/features.csv
    - models/label_encoders.joblib
  train_eval:
    cmd: bash -c 'set -a; [ -f .env ] && . .env || true; set +a; python src/models/train_model.py'
    deps:
    - data/preprocessed/features.csv
    - src/models/train_model.py
    params:
    - src/config/model_config.yaml:
    outs:
    - data/metrics/training_report.txt
    - models/trained_model.joblib
    - models/trained_model_metadata.joblib
    metrics:
    - data/metrics/training_metrics.json:
        cache: false
  test_prediction:
    cmd: bash -c 'set -a; [ -f .env ] && . .env || true; set +a; python src/models/predict_model.py'
    deps:
    - models/label_encoders.joblib
    - models/trained_model.joblib
    - models/trained_model_metadata.joblib
    - src/models/predict_model.py
    params:
    - src/models/test_features.json:
