{
 "title": "API Performance",
 "description": "Monitors the performance of the API by the request rate, the latency, and the error rate",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency by Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_request_duration_seconds_bucket[5m])) by (endpoint, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Endpoint",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total{status_code!=\"200\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}