{
 "title": "Model Performance & Drift",
 "description": "Monitors the model performance and data drift by Accuracy, Prediction, Recall, and F1-Score as well as the data drift detected status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "F1 Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_f1_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Precision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_precision_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recall",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_recall_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Drift Detected Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_drift_status", "legendFormat": "__auto" }
   ]
  }
 ]
}